UUID : '0000f22e-0000-1000-8000-00805f9b34fb'
START_TIME : ['00:46:50', '00:49:50', '00:52:50', '00:55:50', '00:58:50', '01:01:50', '01:04:50', '01:07:50']
END_TIME : ['00:49:00', '00:52:00', '00:55:00', '00:58:00', '01:01:00', '01:04:00', '01:07:00', '01:10:00']
LABEL_LIST : [0, 1, 2, 3, 4, 5, 6, 7]
# START_TIME : ['01:07:50', '01:04:50', '01:01:50', '00:58:50', '00:55:50', '00:52:50', '00:49:50', '00:46:50']
# END_TIME : ['01:10:00', '01:07:00', '01:04:00', '01:01:00', '00:58:00', '00:55:00', '00:52:00', '00:49:00']
# LABEL_LIST : [7, 6, 5, 4, 3, 2, 1, 0]
BEFORE_DIR : './before/U19e_outdoor1201/'
AFTER_DIR : './after/U19e_outdoor1201/'
OUTPUT_DIR: 'output'
FILE : 'sniffer_'
FILE_TYPE : 'csv'
OUTPUT_NAME : 'U19e_outdoor1201'
AP_NUMS : 6
AP_NAME : ['zero', 'one', 'two', 'three', 'four', 'five']

MODEL :
  TYPE : 'LSTM'
  INIT_WEIGHTS : true
  #PRETRAINED : 'output/U19e_outdoor1201/checkpoint_lstm.pth'
  #PRETRAINED : 'output/U19e_outdoor1201/checkpoint.pth'
  #PRETRAINED : 'output/sharp4025_test2/checkpoint.pth'

TRAIN :
  BATCH_SIZE : 32
  SHUFFLE : true
  BEGIN_EPOCH : 0
  END_EPOCH : 400
  OPTIMIZER : adam
  LR : 0.001
  LR_FACTOR : 0.1

TEST :
  #RSSI_LIST : [ [-42, -103], [-54, -96], [-55, -99], [-59, -96]] # U19e
  #RSSI_LIST : [ [-48, -103], [-52, -95], [-30, -97], [-48, -91]] # Sharp
  #RSSI_LIST : [ [-38, -96], [-31, -93], [-26, -93], [-29, -97]] # U19e outdoor1
  #RSSI_LIST : [ [-44, -95], [-28, -101], [-11, -97], [-28, -96]] # U19e outdoor2
  RSSI_LIST : [[-41, -98], [-30, -102], [-28, -101], [-28, -96], [-30, -98], [-33, -95]] # U19e outdoor3

